---
- name: "clean up server"
  become: true
  shell: "sudo rm -rf *"

- name: "git clone repo"
  become: true
  shell: "git clone https://github.com/trungleit0108/devops-cicd.git"

- name: "install dependency"
  become: true
  shell: "sudo npm install"
  args:
    chdir: "/home/ubuntu/devops-cicd/backend"

- name: "install peers dependency"
  become: true
  shell: "sudo npm install -g npm-install-peers"
  args:
    chdir: "/home/ubuntu/devops-cicd/backend"

- name: "build backend server"
  become: true
  shell: "npm run build"
  args:
    chdir: "/home/ubuntu/devops-cicd/backend"

- name: "run backend server"
  become: true
  shell: "pm2 start npm --name 'udapeople' -- start"
  args:
    chdir: "/home/ubuntu/devops-cicd/backend"
  async: 45
  poll: 0
